"""add language and update user timestamps

Revision ID: 5039d9660eda
Revises: aaf4d331df2f
Create Date: 2026-08-10 12:27:25.755282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5039d9660eda'
down_revision: Union[str, Sequence[str], None] = 'aaf4d331df2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "users",
        sa.Column(
            "language",
            sa.String(length=2),
            nullable=False,
            server_default="en",
        ),
    )

    op.alter_column(
        "users",
        "language",
        server_default=None,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language')
    # ### end Alembic commands ###
